// <auto-generated />
namespace Squirrel.Migrations
{
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    public sealed partial class AddLatLong : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(AddLatLong));
        
        string IMigrationMetadata.Id
        {
            get { return "201309031815365_AddLatLong"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
