// <auto-generated />
namespace Squirrel.Migrations
{
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    public sealed partial class ReminderUserId : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(ReminderUserId));
        
        string IMigrationMetadata.Id
        {
            get { return "201307282019475_ReminderUserId"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
